"""modify User

Revision ID: 7fe0ac0b7781
Revises: 9ec16a69b38b
Create Date: 2020-07-13 16:43:24.729026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe0ac0b7781'
down_revision = '9ec16a69b38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('memeber_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'memeber_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
