"""add auth

Revision ID: 66716c18cc81
Revises: 963588accea7
Create Date: 2020-07-12 23:52:11.664854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66716c18cc81'
down_revision = '963588accea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pwd_hash', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pwd_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
