"""Initial migration.

Revision ID: 963588accea7
Revises: 
Create Date: 2020-07-12 16:58:08.548190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '963588accea7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderItems')
    op.drop_table('Orders')
    op.drop_table('Products')
    op.drop_table('Employee')
    op.drop_table('Customers')
    op.drop_table('Vendors')
    op.drop_table('OrdersCopy')
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.create_table('OrdersCopy',
    sa.Column('order_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=False),
    sa.Column('cust_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('vend_web', mysql.CHAR(length=254), server_default=sa.text("''"), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Vendors',
    sa.Column('vend_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('vend_name', mysql.CHAR(length=50), nullable=False),
    sa.Column('vend_address', mysql.CHAR(length=50), nullable=True),
    sa.Column('vend_city', mysql.CHAR(length=50), nullable=True),
    sa.Column('vend_state', mysql.CHAR(length=5), nullable=True),
    sa.Column('vend_zip', mysql.CHAR(length=10), nullable=True),
    sa.Column('vend_country', mysql.CHAR(length=50), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Customers',
    sa.Column('cust_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('cust_name', mysql.CHAR(length=50), nullable=False),
    sa.Column('cust_address', mysql.CHAR(length=50), nullable=True),
    sa.Column('cust_city', mysql.CHAR(length=50), nullable=True),
    sa.Column('cust_state', mysql.CHAR(length=5), nullable=True),
    sa.Column('cust_zip', mysql.CHAR(length=10), nullable=True),
    sa.Column('cust_country', mysql.CHAR(length=50), nullable=True),
    sa.Column('cust_contact', mysql.CHAR(length=50), nullable=True),
    sa.Column('cust_email', mysql.CHAR(length=255), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Employee',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Salary', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Name', mysql.CHAR(length=20), nullable=True),
    sa.Column('ManagerId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sex', mysql.CHAR(length=1), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Products',
    sa.Column('prod_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('vend_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('prod_name', mysql.CHAR(length=255), nullable=False),
    sa.Column('prod_price', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('prod_desc', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Orders',
    sa.Column('order_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=False),
    sa.Column('cust_id', mysql.CHAR(length=10), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('OrderItems',
    sa.Column('order_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_item', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prod_id', mysql.CHAR(length=10), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('item_price', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
